// Generated by scripts/build-body-textures.mjs. Do not edit by hand.
// Content-hashed URLs of the equirectangular body textures (u = 0.5 at
// longitude 0, east to the right). Sources/licences: public/textures/bodies/manifest.json.
export const BODY_TEXTURE_URLS = {
  "earth": "/textures/bodies/earth.20cbdc721e.jpg",
  "earth-aux": "/textures/bodies/earth-aux.72983cf4c7.jpg",
  "moon": "/textures/bodies/moon.bfc3e41d57.jpg",
  "mercury": "/textures/bodies/mercury.76b41a1883.jpg",
  "venus": "/textures/bodies/venus.2604f72fc4.jpg",
  "mars": "/textures/bodies/mars.fca3025fb1.jpg",
  "jupiter": "/textures/bodies/jupiter.359d9333ee.jpg",
  "saturn": "/textures/bodies/saturn.d7e1dd9d96.jpg",
  "saturn-ring": "/textures/bodies/saturn-ring.3700327419.png",
  "uranus": "/textures/bodies/uranus.ae0b6c9261.jpg",
  "neptune": "/textures/bodies/neptune.584c4ff640.jpg",
  "io": "/textures/bodies/io.18ad042ad9.jpg",
  "europa": "/textures/bodies/europa.8862349212.jpg",
  "ganymede": "/textures/bodies/ganymede.bf9713c0a4.jpg",
  "callisto": "/textures/bodies/callisto.8a82737de0.jpg",
  "mimas": "/textures/bodies/mimas.f6149de303.jpg",
  "enceladus": "/textures/bodies/enceladus.d56cb28ada.jpg",
  "tethys": "/textures/bodies/tethys.28102f45d0.jpg",
  "dione": "/textures/bodies/dione.f4ac5b059a.jpg",
  "rhea": "/textures/bodies/rhea.6d3a256891.jpg",
  "titan": "/textures/bodies/titan.4fdd6cc65a.jpg",
  "iapetus": "/textures/bodies/iapetus.66c9613356.jpg",
  "miranda": "/textures/bodies/miranda.aaede9109b.jpg",
  "ariel": "/textures/bodies/ariel.559ad5f645.jpg",
  "umbriel": "/textures/bodies/umbriel.c037f392dc.jpg",
  "titania": "/textures/bodies/titania.dd856f3ade.jpg",
  "oberon": "/textures/bodies/oberon.8130c3bb10.jpg",
  "triton": "/textures/bodies/triton.3575b10f07.jpg",
  "pluto": "/textures/bodies/pluto.c72536bba3.jpg",
  "charon": "/textures/bodies/charon.a25b4b3815.jpg",
  "ceres": "/textures/bodies/ceres.5cadc19ab8.jpg",
  "eris": "/textures/bodies/eris.7a1c9fcb6c.jpg",
  "haumea": "/textures/bodies/haumea.292366a45d.jpg",
  "makemake": "/textures/bodies/makemake.c8142d9ff5.jpg"
} as const;

export type BodyTextureId = keyof typeof BODY_TEXTURE_URLS;
